run('DonneesProjetM8.m');
X_Mat=[TabModMat_School,TabModMat_Sex,Mat_Age,TabModMat_Address,TabModMat_Famsize,TabModMat_Pstatus,Mat_Medu,Mat_Fedu,TabModMat_Mjob,TabModMat_Fjob,TabModMat_Reason,TabModMat_Guardian,Mat_Traveltime,Mat_Studytime,Mat_Failures,TabModMat_Schoolsup,TabModMat_Famsup,TabModMat_Paid,TabModMat_Activities,TabModMat_Nursery,TabModMat_Higher,TabModMat_Internet,TabModMat_Romantic,Mat_Famrel,Mat_Freetime,Mat_Goout,Mat_Dalc,Mat_Walc,Mat_Health,Mat_Absences,Mat_G1,Mat_G2,Mat_G3];
Var_Name=[' School    ';' Sex       ';' Age       ';' Address   ';' Famsize   ';
' Pstatus   ';' Medu      ';' Fedu      ';' Mjob      ';' Fjob      ';' Reason    ';
' Guardian  ';' Traveltime';' Studytime ';' Failures  ';' Schoolsup ';' Famsup    ';
' Paid      ';' Activities';' Nursery   ';' Higher    ';' Internet  ';' Romantic  ';
' Famrel    ';' Freetime  ';' Goout     ';' Dalc      ';' Walc      ';' Health    ';
' Absences  ';' 1ereNote  ';' 2emeNote  ';' NoteFinale'];
[n p]=size(X_Mat);

%% Etude des notes finales
Mat_G3_classe=sort(Mat_G3);
[modalites N]=unique(Mat_G3_classe);
effectifs=[diff(N);1];
effectifs_cumules=cumsum(effectifs);
frequences=effectifs/n;
frequences_cumulees=effectifs_cumules/n;
frequences_corrigees(1,1)=frequences_cumulees(1);
for i=2:length(modalites)
    frequences_corrigees(i,1)=frequences_cumulees(i)-0.5*(frequences_cumulees(i)-frequences_cumulees(i-1));
end;
figure;
%plot(modalites,frequences_cumulees); 
set(gcf,'Color',[1,1,1])
plot(modalites,frequences_cumulees,'o-') ; hold on
for i=1:length(modalites)-1
    plot([modalites(i) modalites(i+1)],[frequences_cumulees(i) frequences_cumulees(i)],'r');
    plot([modalites(i+1) modalites(i+1)],[frequences_cumulees(i) frequences_cumulees(i+1)],'r');
end
title('Fonction de repartition des notes finales des eleves');
xlabel('Notes finales');
ylabel('Frequences cumulees');
grid on;
moyenne_notes=mean(Mat_G3);
figure;
boxPlot(Mat_G3);
title('Notes finales des eleves');
ylabel('Notes');
grid on;
indice_echec=max(find(modalites<10));
taux_echec=frequences_cumulees(indice_echec)*100;
effectif_echec=effectifs_cumules(indice_echec);
histogramme=[effectif_echec,n-effectif_echec];
figure;
bar(histogramme,'r');
title('Validation de la matiere');
ylabel('Nombre d''eleves');
set(gca,'XTickLabel',{'echec','reussite'})
indice_passable_max=max(find(modalites>=10 & modalites<12));
effectif_passable=effectifs_cumules(indice_passable_max)-effectifs_cumules(indice_echec);
indice_assezbien_max=max(find(modalites>=12 & modalites<14));
effectif_assezbien=effectifs_cumules(indice_assezbien_max)-effectifs_cumules(indice_passable_max);
indice_bien_max=max(find(modalites>=14 & modalites<16));
effectif_bien=effectifs_cumules(indice_bien_max)-effectifs_cumules(indice_assezbien_max);
indice_tresbien_max=max(find(modalites>=16 & modalites<18));
effectif_tresbien=effectifs_cumules(indice_tresbien_max)-effectifs_cumules(indice_bien_max);
effectif_excellent=n-effectifs_cumules(indice_tresbien_max);
histogramme=[effectif_echec,effectif_passable,effectif_assezbien,effectif_bien,effectif_tresbien,effectif_excellent];
figure;
bar(histogramme);
title('Mentions obtenues par les eleves');
ylabel('Nombre d''eleves');
set(gca,'XTickLabel',{'echec','aucune','assez bien','bien','tres bien','excellent'});
%% Analyse en composantes principales
moyenne=ones(n,1)*mean(X_Mat);
ecart_type=ones(n,1)*std(X_Mat);
Xc_Mat=(X_Mat-moyenne);% matrice centree
Xn_Mat=Xc_Mat./ecart_type;% matrice centree et reduite
rho=Xn_Mat'*Xn_Mat/n;% matrice des correlations
[V D]=eig(Xn_Mat'*Xn_Mat);% calcul des vecteurs et valeurs propres
lambda=diag(D);% valeurs propres
info=lambda/sum(lambda)*100;% pourcentage d'information porte par chacune des composantes principales
Vn = V*sqrt(D(1:p,1:p)/n);
t=0:0.01:2*pi+0,01;
figure;
plot(Vn(:,p),Vn(:,p-1),'*');
title('Representation des variables avec deux l''axes de l''ACP');
xlabel('axe 1 : 11.74 % d''information');
ylabel('axe 2 : 7.69 % d''information');
hold on;
plot(cos(t),sin(t));
grid on;
for i=1:p % affichage du nom des variables sur le graphique
    text(Vn(i,p),Vn(i,p-1),Var_Name(i,:),'FontSize',9);
end;
%% Regression lineaire simple
%% G1 explicative G3 a expliquer
X=[Mat_G1 ones(n,1)];
[n,p]=size(X);
alpha_G1=X\Mat_G3;% matrice contenant les parametres de la regression
y_pred_G1=X*alpha_G1;% valeurs predites par la regression
residus_G1=Mat_G3-y_pred_G1;% erreurs entre les valeurs predites et les valeurs reelles
H = X*inv(X'*X)*X';% projecteur
h=diag(H);
variance_estimee = residus_G1'*residus_G1/(n-p-1);
residus_standardises = residus_G1./sqrt(variance_estimee*(1-h));
contributions_G1 = residus_standardises.*residus_standardises.*(h./(p.*(1-h)));
R2_G1=sum((y_pred_G1-mean(Mat_G3)).^2)/sum((Mat_G3-mean(Mat_G3)).^2);% coefficient de determination
figure;
plot(Mat_G1,y_pred_G1,'r');
title('Regression lineaire');
xlabel('Premieres notes');
ylabel('Notes finales');
hold on;
plot(Mat_G1,Mat_G3,'o');
figure;
plot (Mat_G3,residus_G1,'+r');
title('Residus');
xlabel('Notes finales');
ylabel('Modalites');
figure;
plot(Mat_G3,contributions_G1,'+r');
title('Contributions');
xlabel('Notes finales');
ylabel('Modalites');
% elimination des point aberrants c'est a dire des notes egales a 0
indices_aberrants=find(Mat_G3==0);
Mat_G1stock=Mat_G1;
Mat_G1(indices_aberrants)=[];
Mat_G3stock=Mat_G3;
Mat_G3(indices_aberrants)=[];
[n,p]=size(Mat_G1);
X=[Mat_G1 ones(n,1)];
[n,p]=size(X);
alpha_G1bis=X\Mat_G3;
y_pred_G1bis=X*alpha_G1bis;
residus_G1bis=Mat_G3-y_pred_G1bis;
H = X*inv(X'*X)*X';
h=diag(H);
variance_estimee = residus_G1bis'*residus_G1bis/(n-p-1);
residus_standardises = residus_G1bis./sqrt(variance_estimee*(1-h));
contributions_G1bis = residus_standardises.*residus_standardises.*(h./(p.*(1-h)));
R2_G1bis=sum((y_pred_G1bis-mean(Mat_G3)).^2)/sum((Mat_G3-mean(Mat_G3)).^2);
figure;
plot(Mat_G1,y_pred_G1bis,'r');
title('Regression lineaire');
xlabel('Premieres notes');
ylabel('Notes finales');
hold on;
plot(Mat_G1,Mat_G3,'o');
figure;
plot (Mat_G3,residus_G1bis,'o');
title ('Residus');
xlabel('Notes finales');
ylabel('Modalites');
[modalites N]=unique(sort(residus_G1bis));
effectifs=[diff(N);1];
figure;
bar(modalites,effectifs);
title('Distribution des residus');
xlabel('Modalites');
ylabel('Effectifs');
figure;
plot(Mat_G3,contributions_G1bis,'o');
title('Contributions');
xlabel('Notes finales');
ylabel('Modalites');

%% G2 explicative G3 a expliquer
Mat_G3=Mat_G3stock;
[n,p]=size(Mat_G2);
X=[Mat_G2 ones(n,1)];
[n,p]=size(X);
alpha_G2=X\Mat_G3;
y_pred_G2=X*alpha_G2;
residus_G2=Mat_G3-y_pred_G2;
H = X*inv(X'*X)*X';
h=diag(H);
variance_estimee = residus_G2'*residus_G2/(n-p-1);
residus_standardises = residus_G2./sqrt(variance_estimee*(1-h));
contributions_G2 = residus_standardises.*residus_standardises.*(h./(p.*(1-h)));
R2_G2=sum((y_pred_G2-mean(Mat_G3)).^2)/sum((Mat_G3-mean(Mat_G3)).^2);
figure;
plot(Mat_G2,y_pred_G2,'r');
title('Regression lineaire');
xlabel('Deuxiemes notes');
ylabel('Notes finales');
hold on;
plot(Mat_G2,Mat_G3,'o');
figure;
plot (Mat_G3,residus_G2,'+r');
title('Residus');
xlabel('Notes finales');
ylabel('Modalites');
figure;
plot(Mat_G3,contributions_G2,'o');
title('Contributions');
xlabel('Notes finales');
ylabel('Modalites');
% elimination des point aberrants c'est a dire des notes egales a 0
Mat_G2stock=Mat_G2;
Mat_G2(indices_aberrants)=[];
Mat_G3(indices_aberrants)=[];
[n,p]=size(Mat_G2);
X=[Mat_G2 ones(n,1)];
[n,p]=size(X);
alpha_G2bis=X\Mat_G3;
y_pred_G2bis=X*alpha_G2bis;
residus_G2bis=Mat_G3-y_pred_G2bis;
H = X*inv(X'*X)*X';
h=diag(H);
variance_estimee = residus_G2bis'*residus_G2bis/(n-p-1);
residus_standardises = residus_G2bis./sqrt(variance_estimee*(1-h));
contributions_G2bis = residus_standardises.*residus_standardises.*(h./(p.*(1-h)));
R2_G2bis=sum((y_pred_G2bis-mean(Mat_G3)).^2)/sum((Mat_G3-mean(Mat_G3)).^2);
figure;
plot(Mat_G2,y_pred_G2bis,'r');
title('Regression lineaire');
xlabel('Deuxiemes notes');
ylabel('Notes finales');
hold on;
plot(Mat_G2,Mat_G3,'o');
figure;
plot (Mat_G3,residus_G2bis,'+r');
title('Residus')
xlabel('Notes finales');
ylabel('Modalites');
[modalites N]=unique(sort(residus_G2bis));
effectifs=[diff(N);2];
figure;
bar(modalites,effectifs);
title('Distribution des residus');
xlabel('Modalites');
ylabel('Effectifs');
figure;
plot(Mat_G3,contributions_G2bis,'o');
title('Contributions');
xlabel('Notes finales');
ylabel('Modalites');
%% Regression lineaire multiple
%% G1 et G2 explicatives G3 a expliquer
Mat_G1=Mat_G1stock;
Mat_G2=Mat_G2stock;
Mat_G3=Mat_G3stock;
[n p]=size(Mat_G3);
X=[Mat_G1 Mat_G2 ones(n,1)];
[n p]=size(X);
alpha=X\Mat_G3;
y_pred=X*alpha;
residus=Mat_G3-y_pred;
H = X*inv(X'*X)*X';
h=diag(H);
variance_estimee = residus'*residus/(n-p-1);
residus_standardises = residus./sqrt(variance_estimee*(1-h));
contributions= residus_standardises.*residus_standardises.*(h./(p.*(1-h)));
R2=sum((y_pred-mean(Mat_G3)).^2)/sum((Mat_G3-mean(Mat_G3)).^2);
figure;
plot (Mat_G3,residus,'+r');
title('Residus');
xlabel('Notes finales');
ylabel('Modalites');
figure;
plot(Mat_G3,contributions,'o');
title('Contributions');
xlabel('Notes finales');
ylabel('Modalites');
% elimination des point aberrants c'est a dire des notes egales a 0
Mat_G1(indices_aberrants)=[];
Mat_G2(indices_aberrants)=[];
Mat_G3(indices_aberrants)=[];
[n p]=size(Mat_G3);
X=[Mat_G1 Mat_G2 ones(n,1)];
[n p]=size(X);
alpha_bis=X\Mat_G3;
y_pred_bis=X*alpha_bis;
residus_bis=Mat_G3-y_pred_bis;
H = X*inv(X'*X)*X';
h=diag(H);
variance_estimee = residus_bis'*residus_bis/(n-p-1);
residus_standardises = residus_bis./sqrt(variance_estimee*(1-h));
contributions_bis= residus_standardises.*residus_standardises.*(h./(p.*(1-h)));
R2_bis=sum((y_pred_bis-mean(Mat_G3)).^2)/sum((Mat_G3-mean(Mat_G3)).^2);
figure;
plot (Mat_G3,residus_bis,'+r');
title('Residus');
xlabel('Notes finales');
ylabel('Modalites');
[modalites N]=unique(sort(residus_bis));
effectifs=[diff(N);1];
figure;
bar(modalites,effectifs);
title('Distribution des residus');
xlabel('Modalites');
ylabel('Effectifs');
figure;
plot(Mat_G3,contributions_bis,'o');
title('Contributions');
xlabel('Notes finales');
ylabel('Modalites');
%% Comparaison Failures note finale
Mat_G3=Mat_G3stock;
indice_0redoublement=find(Mat_Failures==0);
effectif_0redoublement=Mat_G3(indice_0redoublement);
moyenne_0redoublement=mean(effectif_0redoublement);
figure;
boxPlot(effectif_0redoublement);
title('Notes finales des eleves ayant eu 0 redoublement');
ylabel('Notes');
grid on;
indice_1redoublement=find(Mat_Failures==1);
effectif_1redoublement=Mat_G3(indice_1redoublement);
moyenne_1redoublement=mean(effectif_1redoublement);
figure;
boxPlot(effectif_1redoublement);
title('Notes finales des eleves ayant eu 1 redoublement');
ylabel('Notes');
grid on;
indice_2redoublements=find(Mat_Failures==2);
effectif_2redoublements=Mat_G3(indice_2redoublements);
moyenne_2redoublements=mean(effectif_2redoublements);
figure;
boxPlot(effectif_2redoublements);
title('Notes finales des eleves ayant eu 2 redoublements');
ylabel('Notes');
grid on;
indice_3redoublements=find(Mat_Failures==3);
effectif_3redoublements=Mat_G3(indice_3redoublements);
moyenne_3redoublements=mean(effectif_3redoublements);
figure;
boxPlot(effectif_3redoublements);
title('Notes finales des eleves ayant eu 3 redoublements');
ylabel('Notes');
grid on;
histogramme=[moyenne_0redoublement moyenne_1redoublement moyenne_2redoublements moyenne_3redoublements];
figure;
bar(histogramme);
title('Evolution des moyennes en fonction du nombre de redoublement des eleves');
ylabel('Moyenne des notes finales obtenues');
set(gca,'XTickLabel',{'0 redoublement','1 redoublement','2 redoublements','3 redoublements'});
%% Comparaison Medu Note finale
indice_0degre_education_mere=find(Mat_Medu==0);
effectif_0degre_education_mere=Mat_G3(indice_0degre_education_mere);
indice_1degre_education_mere=find(Mat_Medu==1);
effectif_1degre_education_mere=Mat_G3(indice_1degre_education_mere);
moyenne_1degre_education_mere=mean(effectif_1degre_education_mere);
figure;
boxPlot(effectif_1degre_education_mere);
title('Notes finales des eleves ayant une mere avec un niveau 1 d''education');
ylabel('Notes');
grid on;
indice_2degre_education_mere=find(Mat_Medu==2);
effectif_2degre_education_mere=Mat_G3(indice_2degre_education_mere);
moyenne_2degre_education_mere=mean(effectif_2degre_education_mere);
figure;
boxPlot(effectif_2degre_education_mere);
title('Notes finales des eleves ayant une mere avec un niveau 2 d''education');
ylabel('Notes');
grid on;
indice_3degre_education_mere=find(Mat_Medu==3);
effectif_3degre_education_mere=Mat_G3(indice_3degre_education_mere);
moyenne_3degre_education_mere=mean(effectif_3degre_education_mere);
figure;
boxPlot(effectif_3degre_education_mere);
title('Notes finales des eleves ayant une mere avec un niveau 3 d''education');
ylabel('Notes');
grid on;
indice_4degre_education_mere=find(Mat_Medu==4);
effectif_4degre_education_mere=Mat_G3(indice_4degre_education_mere);
moyenne_4degre_education_mere=mean(effectif_4degre_education_mere);
figure;
boxPlot(effectif_4degre_education_mere);
title('Notes finales des eleves ayant une mere avec un niveau 4 d''education');
ylabel('Notes');
grid on;
histogramme=[moyenne_1degre_education_mere moyenne_2degre_education_mere moyenne_3degre_education_mere moyenne_4degre_education_mere];
figure;
bar(histogramme);
title('Evolution des moyennes en fonction du niveau d''education des meres des eleves');
ylabel('Moyenne des notes finales obtenues');
set(gca,'XTickLabel',{'Niveau 1','Niveau 2','Niveau 3','Niveau 4'});
%% Comparaison Fedu Note finale
indice_0degre_education_pere=find(Mat_Fedu==0);
effectif_0degre_education_pere=Mat_G3(indice_0degre_education_pere);
indice_1degre_education_pere=find(Mat_Fedu==1);
effectif_1degre_education_pere=Mat_G3(indice_1degre_education_pere);
moyenne_1degre_education_pere=mean(effectif_1degre_education_pere);
figure;
boxPlot(effectif_1degre_education_pere);
title('Notes finales des eleves ayant un pere avec un niveau 1 d''education');
ylabel('Notes');
grid on;
indice_2degre_education_pere=find(Mat_Fedu==2);
effectif_2degre_education_pere=Mat_G3(indice_2degre_education_pere);
moyenne_2degre_education_pere=mean(effectif_2degre_education_pere);
figure;
boxPlot(effectif_2degre_education_pere);
title('Notes finales des eleves ayant un pere avec un niveau 2 d''education');
ylabel('Notes');
grid on;
indice_3degre_education_pere=find(Mat_Fedu==3);
effectif_3degre_education_pere=Mat_G3(indice_3degre_education_pere);
moyenne_3degre_education_pere=mean(effectif_3degre_education_pere);
figure;
boxPlot(effectif_3degre_education_pere);
title('Notes finales des eleves ayant un pere avec un niveau 3 d''education');
ylabel('Notes');
grid on;
indice_4degre_education_pere=find(Mat_Fedu==4);
effectif_4degre_education_pere=Mat_G3(indice_4degre_education_pere);
moyenne_4degre_education_pere=mean(effectif_4degre_education_pere);
figure;
boxPlot(effectif_4degre_education_pere);
title('Notes finales des eleves ayant un pere avec un niveau 4 d''education');
ylabel('Notes');
grid on;
histogramme=[moyenne_1degre_education_pere moyenne_2degre_education_pere moyenne_3degre_education_pere moyenne_4degre_education_pere];
figure;
bar(histogramme);
title('Evolution des moyennes en fonction du niveau d''education des peres des eleves');
ylabel('Moyenne des notes finales obtenues');
set(gca,'XTickLabel',{'Niveau 1','Niveau 2','Niveau 3','Niveau 4'});
%% Comparaison Age note finale
indice_15ans=find(Mat_Age==15);
effectif_15ans=Mat_G3(indice_15ans);
moyenne_15ans=mean(effectif_15ans);
figure;
boxPlot(effectif_15ans);
title('Notes finales des eleves ayant 15 ans');
ylabel('Notes');
grid on;
indice_16ans=find(Mat_Age==16);
effectif_16ans=Mat_G3(indice_16ans);
moyenne_16ans=mean(effectif_16ans);
figure;
boxPlot(effectif_16ans);
title('Notes finales des eleves ayant 16 ans');
ylabel('Notes');
grid on;
indice_17ans=find(Mat_Age==17);
effectif_17ans=Mat_G3(indice_17ans);
moyenne_17ans=mean(effectif_17ans);
figure;
boxPlot(effectif_17ans);
title('Notes finales des eleves ayant 17 ans');
ylabel('Notes');
grid on;
indice_18ans=find(Mat_Age==18);
effectif_18ans=Mat_G3(indice_18ans);
moyenne_18ans=mean(effectif_18ans);
figure;
boxPlot(effectif_18ans);
title('Notes finales des eleves ayant 18 ans');
ylabel('Notes');
grid on;
indice_19ans=find(Mat_Age==19);
effectif_19ans=Mat_G3(indice_19ans);
moyenne_19ans=mean(effectif_19ans);
figure;
boxPlot(effectif_19ans);
title('Notes finales des eleves ayant 19 ans');
ylabel('Notes');
grid on;
indice_20ans=find(Mat_Age==20);
effectif_20ans=Mat_G3(indice_20ans);
indice_21ans=find(Mat_Age==21);
effectif_21ans=Mat_G3(indice_21ans);
indice_22ans=find(Mat_Age==22);
effectif_22ans=Mat_G3(indice_22ans);
histogramme=[moyenne_15ans moyenne_16ans moyenne_17ans moyenne_18ans moyenne_19ans];
figure;
bar(histogramme,'r');
title('Evolution des moyennes en fonction de l''age des eleves');
ylabel('Moyenne des notes finales obtenues');
set(gca,'XTickLabel',{'15 ans','16 ans','17 ans','18 ans','19 ans'});
